-- Grupo2: Raul Molina, Pablo Garcia, Alvaro Lopez
-- Renombrar tablas
ALTER TABLE DEPART RENAME TO DEPARTS;
ALTER TABLE EMPLE RENAME TO EMPLEADOS;

-- Tabla PRESUPUESTOS
CREATE TABLE PRESUPUESTOS(
	DEPT_NO NUMBER(4) NOT NULL,  
	ANIO NUMBER(4) NOT NULL,
	IMPORTE NUMBER(10,2),

	CONSTRAINT PK_PRESUPUESTOS PRIMARY KEY (ANIO, DEPT_NO),
	CONSTRAINT FK_PRESUPUSTOS_DEPARTS FOREIGN KEY (DEPT_NO) REFERENCES DEPARTS(DEPT_NO),
	CONSTRAINT CK_IMPORTE CHECK (IMPORTE > 0)
);

-- Tabla EMPLEADOS
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_EMP_NO_NN CHECK (EMP_NO IS NOT NULL);
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_APELLIDO_NN CHECK (APELLIDO IS NOT NULL);

ALTER TABLE EMPLEADOS ADD TIPO VARCHAR2(13);

ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_TIPO CHECK (TIPO IN ('COORDINADOR', 'TESORERO'));
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_SALARIO CHECK (SALARIO > 1221);

-- Actualizar los salarios y comisiones a euros
-- Por cada empleado, dividir el salario y la comisión entre 166.386 y redondear a dos decimales
UPDATE EMPLEADOS 
SET SALARIO = ROUND(SALARIO / 166.386, 2),
    COMISION = ROUND(NVL(COMISION, 0) / 166.386, 2);
					
