CREATE TABLE DEPART(
  DEPT_NO NUMBER(2) NOT NULL,
  DNOMBRE VARCHAR2(14),
  LOC VARCHAR2(14),
  CONSTRAINT PK_DEPART PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMPLE(
  EMP_NO    NUMBER(4),
  APELLIDO  VARCHAR2(10) NOT NULL UNIQUE,
  OFICIO    VARCHAR2(10),
  DIR  NUMBER(4) NOT NULL,
  FECHA_ALT DATE,
  SALARIO   NUMBER(10),
  COMISION  NUMBER(10),
  DEPT_NO   NUMBER(2) NOT NULL,
  CONSTRAINT PK_EMPLE PRIMARY KEY (EMP_NO),
  CONSTRAINT FK_EMPLE_EMPLE FOREIGN KEY (DIR) REFERENCES EMPLE,
  CONSTRAINT FK_EMPLE_DEPART FOREIGN KEY (DEPT_NO) REFERENCES DEPART
);

CREATE TABLE PRESUPUESTO (
DEPT_NO NUMBER(4) NOT NULL,
ANIO DATE,
IMPORTE NUMBER(10),
CONSTRAINT PK_PRESUPUESTO PRIMARY KEY (ANIO,DEPT_NO),
CONSTRAINT FK_PRESUPUESTO_DEPART FOREIGN KEY(DEPT_NO) REFERENCES DEPART
);

CREATE TABLE COORDINADOR (
EMP_NO NUMBER(4),
DEPT_NO NUMBER(2) NOT NULL,
CONSTRAINT PK_COORDINADOR PRIMARY KEY (EMP_NO),
CONSTRAINT FK_COORDINADOR_EMPLE FOREIGN KEY(EMP_NO) REFERENCES EMPLE,
CONSTRAINT FK_COORDINADOR_DEPART FOREIGN KEY(DEPT_NO) REFERENCES DEPART
);

CREATE TABLE TESORERO (
EMP_NO NUMBER(4),
DEPT_NO NUMBER(2) NOT NULL,
CONSTRAINT PK_TESORERO PRIMARY KEY (EMP_NO),
CONSTRAINT FK_TESORERO_EMPLE FOREIGN KEY(EMP_NO) REFERENCES EMPLE,
CONSTRAINT FK_TESORERO_DEPART FOREIGN KEY(DEPT_NO) REFERENCES DEPART
);

